{% set name = "aequilibrae" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aequilibrae-{{ version }}.tar.gz
  sha256: 189b877168ddece934e2992ba15afd742952ce521cc80cea39c78e27bbf3c047

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
    - CFLAGS=-D_LIBCPP_DISABLE_AVAILABILITY  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - cython
  host:
    - python
    - setuptools
    - numpy
    - cython
    - pyarrow 17.0.0
    - pip
  run:
    - python
    - scipy
    - pyaml
    - pyqt
    - cython
    - pyshp
    - requests
    - shapely
    - pandas
    - pyarrow 17.0.0
    - pyproj
    - openmatrix
    - geopandas
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - aequilibrae
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AequilibraE/aequilibrae
  summary: A package for transportation modeling
  license: MIT
  license_file: LICENSE.TXT

extra:
  recipe-maintainers:
    - pedrocamargo
